fooqey_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("fooqey_frontend.urls")),
    path('auth/', include("autentikasi.urls")),
    path('product_info/', include("productinfo.urls")),
    path('transaction/', include("transaction.urls")),
    path('wishlist/', include("wishlist.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('transaksi_cepat/', include("transaksi_cepat.urls")),
    path('cart/', include("keranjang.urls"))
]

transaction/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.transaction, name="transaction"),
    path("checkout/<int:id_barang>", views.checkout, name="checkout"),
    path("cariKupon/<int:persenTarget>", views.cariKupon, name="cariKupon")
]

ulasan/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ulasan, name="ulasan"),
    path("<int:pkTarget>/", views.ulasan, name="ulasan"),
]

transaction/models.py
from django.db import models

# Create your models here.

transaction/forms.py
from django import forms

class CheckoutForm(forms.Form):
    namaPembeli = forms.CharField(max_length=20)
    kodeKupon = forms.CharField(max_length=10, required=False)
    

transaction/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from fooqey_backend.models import Transaksi, Kupon, Barang
from .forms import CheckoutForm

from django.http import JsonResponse
from django.core import serializers


# Create your views here.

def transaction(request):
    transactions = Transaksi.objects.all()
    subtotal_str = ""
    for transaction in transactions:
        subtotal = int(transaction.total)
        subtotal_str = "Rp " + str(subtotal)

    context = {
        'transactions' : transactions,
        'subtotal' : subtotal_str
    }

    return render(request, "transaction/transaction.html", context)

def checkout(request, id_barang):
    barang1 = {}
    try:
        barang1 = Barang.objects.get(pk=id_barang)
    except:
        return redirect('/')
    if request.method == "POST":
        form = CheckoutForm(request.POST)

        if form.is_valid():
            kodeKupon = form.cleaned_data.get('kodeKupon')
            namaPembeli = form.cleaned_data.get('namaPembeli')
            coupon = Kupon.objects.filter(kode=kodeKupon).first()
            if coupon:
                subtotal = int(barang1.harga * (100 - coupon.persen) / 100)
                checkout = Transaksi.objects.create(pembeli = namaPembeli, total = subtotal, kupon = coupon, Barang = barang1)
            else:
                subtotal = int(barang1.harga)
                checkout = Transaksi.objects.create(pembeli = namaPembeli, total = subtotal, Barang = barang1)

            return redirect('/')
    else:
        form = CheckoutForm()

    return render(request, "transaction/checkout.html", {'form' : form, 'barang1' : barang1})

def cariKupon(request, persenTarget):
    kupon = Kupon.objects.filter(persen = persenTarget).values()
    return JsonResponse({"kuponList":list(kupon)})

transaction/templates/transaction/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Fooqey Shop - Check Out{% endblock title %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'transaction/transaction.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'transaction/checkout.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock header %}

{% block content %}
{{block.super}}
<div class="mx-5 my-3 main-checkout">
    <div class="title-checkout">
        <h2>Check Out</h2>
    </div>

    <p><strong>* Please fill out the form below to proceed to check out</strong></p>

    <div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="namaPembeli">Name</label>
              {{ form.namaPembeli }}
              <!-- <input class="form-control" type="text"  name="namaPembeli" placeholder="Enter your name"> -->
            </div>
            <div class="form-group">
              <label for="kodeKupon">Coupon Code</label>
              {{ form.kodeKupon }}
              <!-- <input type="text" class="form-control" for="kodeKupon" name="kodeKupon" placeholder="Enter the code of the coupon you wish to apply"> -->
            </div>

            <div class="d-flex container">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Kupon berapa persen?</span>
                    </div>
                    <input type="text" class="form-control" id="persen" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                </div>

                <div>
                    <a class="btn btn-success" id="cariKupon" style="color: white;">Cari!</a>
                </div>
            </div>

            <div class="dropdown container d-flex justify-content-center">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span>
                        Kupon!
                    </span>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="listKupon">
                    <p>Cari kupon dulu!</p>
                </div>
            </div>
        
            <div class="itemProduct mt-5 p-3">
                <div class="row">
                    <div class="col-2">
                        <img class="img-fluid" src="https://via.placeholder.com/300">
                    </div>
                    <div class="col-5">
                        <div class="d-flex h-100">
                            <div class="flex-wrapper d-flex flex-column justify-content-center align-self-md-center align-self-start">
                                <strong class="itemTitle">{{barang1.nama}}</strong>
                                <p class="itemPrice">Rp {{barang1.harga}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-5 d-flex align-items-center justify-content-between">
                        <div class="row w-100">
                            <div class="col-12 pr-0 text-right totalPrice">
                                <span class="d-block"><strong>Total : <br> Rp {{barang1.harga}} </strong></span>
                                <!-- <span class="d-block mt-2" style="color: rgb(129, 43, 43);"><strong>Grand Total : <br> Rp {{subtotal}} </strong></span> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>    
    
            <div class="mt-5 container">
                <div class="row" style="justify-content: flex-end;">
                    <input type=submit class="col-3 btn-checkout" value="Check Out">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

{% block script %}
<script>
$(document).ready(function () {
    $("#cariKupon").click(function() {
        var searchedCoupon = $("#persen").val();
        console.log("Searched coupon percent: " + searchedCoupon + "%");

        if (searchedCoupon == "") {
            alert("Isi persenan kupon terlebih dahulu!");
        } else {
            $("#listKupon").empty();

            $.get(`/transaction/cariKupon/${searchedCoupon}`, function(data) {
                console.log(data)
                for (var kupon of data.kuponList) {
                    console.log(kupon.kode)
                    $("#listKupon").append (
                        `<a class="dropdown-item ${kupon.kode}" href="#" kode="${kupon.kode}">${kupon.kode}</a>`
                    )
                }

            })

        }
    })

    $("#listKupon").click(function(event) {
        kuponTarget = event.target;

        if ($(kuponTarget).hasClass("dropdown-item")) {
            console.log("jalan bos")
            var kode = $(kuponTarget).attr("kode");
            console.log(kode);

            var buttonDD = $("#dropdownMenuButton");


            $("#dropdownMenuButton").text(`${kode}`);

            $("#id_kodeKupon").val(`${kode}`);
        }
    })
})
</script>
{% endblock script %}

transaction/templates/transaction/transaction.html
{% extends 'base.html' %}
{% load static %}

{% block title %}FOOQEY SHOP - Transaction History{% endblock title %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'transaction/transaction.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
{% endblock header %}

{% block content %}
{{block.super}}
<div class="mx-5 my-3 main-title">
    <div>
        <h2>Transaction History</h2>
        <!-- <a href="{% url 'checkout' %)">checkout</a> -->
    </div>

    <div class="mt-5 d-flex flex-column">
        <div class="row justify-content-center ml-1 title">
            <div class="col">
                <p>Order</p>
            </div>
            <div class="col">
                <p>Name</p>
            </div>
            <div class="col">
                <p>Date</p>
            </div>
            <div class="col">
                <p>Item</p>
            </div>
            <div class="col">
                <p>Coupon</p>
            </div>
            <div class="col">
                <p>Subtotal</p>
            </div>
        </div>

        {% for transaction in transactions %}
        <div class="card entry my-3 mr-5">
            <div class="card-body row">
                <p class="col">{{transaction.id}}</p>
                <p class="col">{{transaction.pembeli}}</p>
                <p class="col">{{transaction.tanggal}}</p>
                <p class="col">{{transaction.Barang.nama}}</p>
                <p class="col">{{transaction.kupon.kode}}</p>
                <p class="col">{{transaction.total}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block script %}
{% endblock script %}